os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
services:
  - postgresql
before_script:
  - psql -c 'create database users;' -U postgres
install:
  - eval "$(curl -sL swift.vapor.sh/travis)"
script:
  - eval "$(curl -sL swift.qutheory.io/ci)"
  - eval "$(curl -sL swift.qutheory.io/codecov)"